services:
  postgres-db-stream:
    image: postgres:17
    ports:
      - "25433:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USERNAME_DB}
      POSTGRES_PASSWORD: ${USERNAME_DB}
      POSTGRES_DB: ${DB_NAME}
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8087:8079"
    env_file:
      - ./.env
    depends_on:
      - postgres-db-stream